name: Deploy to Maven Central & GitHub
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          servers: '[{ "id": "ossrh", "username": "jplag", "password": "${{ secrets.OSSRH_TOKEN }}" }]'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PW }}
      - name: Publish package
        run: mvn -P deployment -U -B deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.PGP_PW }}

  publish-release-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build JPlag
        run: mvn -U -B clean package assembly:single

      - name: Attach CLI to Release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cli/target/jplag-*-jar-with-dependencies.jar
          fail_on_unmatched_files: true
