name: Report Viewer e2e Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/report-viewer-e2e.yml"
      - "report-viewer/**"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and Build 🔧
        working-directory: report-viewer
        run: |
          npm install
          npm run build
        
      - name: Install playwright 🔧
        working-directory: report-viewer
        run: npx playwright install --with-deps

      - name: Run tests 🧪
        working-directory: report-viewer
        run: |
          npm run test:e2e

      - name: Upload test results 📤
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            report-viewer/test-results
            report-viewer/playwright-report
          retention-days: 30